/** Importa productos de proveedores con previsualización y asociación de columnas. */
"use client";

import { useMemo, useRef, useState } from "react";
import { FileSpreadsheet, LoaderCircle, Upload, X } from "lucide-react";
import { toast } from "sonner";
import { useRouter } from "next/navigation";
import { useCierreExterior } from "@/componentes/interaccion/cierre-exterior";

type Sede = { id: string; nombre: string };
type Previsualizacion = { encabezados: string[]; filas: string[][]; numerosFilas: number[]; totalFilas: number; recortado: boolean };
type CampoCompra = "ignorar" | "nombre" | "cantidad" | "costo" | "precio" | "sku";
const campos: Array<{ valor: CampoCompra; etiqueta: string }> = [
  { valor: "ignorar", etiqueta: "No importar" }, { valor: "nombre", etiqueta: "Producto" }, { valor: "cantidad", etiqueta: "Cantidad" }, { valor: "costo", etiqueta: "Costo unitario" }, { valor: "precio", etiqueta: "Precio de venta" }, { valor: "sku", etiqueta: "SKU" },
];
function normalizar(valor: string) { return valor.normalize("NFD").replace(/\p{Diacritic}/gu, "").toLowerCase().replace(/[._-]+/g, " ").replace(/\s+/g, " ").trim(); }
function detectar(valor: string): CampoCompra { const texto = normalizar(valor); if (["nombre", "producto", "articulo", "item", "description"].includes(texto)) return "nombre"; if (["cantidad", "cant", "stock", "unidades"].includes(texto)) return "cantidad"; if (["costo", "coste", "costo unitario", "precio compra"].includes(texto)) return "costo"; if (["precio", "precio venta", "venta"].includes(texto)) return "precio"; if (["sku", "codigo", "codigo producto"].includes(texto)) return "sku"; return "ignorar"; }
function numero(valor: string) { const limpio = valor.replace(/\s/g, "").replace(/\.(?=\d{3}(?:\D|$))/g, "").replace(",", "."); return Number(limpio); }

export function ImportadorCompras({ sedes }: { sedes: Sede[] }) {
  const router = useRouter();
  const [abierto, setAbierto] = useState(false), [cargando, setCargando] = useState(false), [previsualizacion, setPrevisualizacion] = useState<Previsualizacion | null>(null), [asociacion, setAsociacion] = useState<CampoCompra[]>([]), [sedeId, setSedeId] = useState(sedes[0]?.id ?? ""), [proveedor, setProveedor] = useState(""), [mensaje, setMensaje] = useState("");
  const dialogo = useRef<HTMLElement>(null);
  useCierreExterior(dialogo, cerrar, abierto);
  const preparados = useMemo(() => !previsualizacion ? [] : previsualizacion.filas.map((fila, indice) => { const datos: Record<string, string | number> = { fila: previsualizacion.numerosFilas[indice] ?? indice + 2 }; asociacion.forEach((campo, columna) => { if (campo !== "ignorar") datos[campo] = fila[columna] ?? ""; }); return datos; }).filter((item) => item.nombre && Number(item.cantidad) > 0 && Number(item.costo) > 0).map((item) => ({ nombre: String(item.nombre), cantidad: Math.floor(Number(item.cantidad)), costo: numero(String(item.costo)), precio: item.precio ? numero(String(item.precio)) : undefined, sku: item.sku ? String(item.sku) : undefined })), [asociacion, previsualizacion]);
  const repetidos = new Set(asociacion.filter((campo) => campo !== "ignorar")).size !== asociacion.filter((campo) => campo !== "ignorar").length;
  async function seleccionar(archivo?: File) { if (!archivo) return; setCargando(true); setMensaje(""); try { const form = new FormData(); form.set("archivo", archivo); const respuesta = await fetch("/api/v1/compras/importacion/previsualizar", { method: "POST", body: form }); const datos = await respuesta.json(); if (!respuesta.ok) throw new Error(datos.mensaje); setPrevisualizacion(datos); setAsociacion(datos.encabezados.map(detectar)); } catch (error) { setMensaje(error instanceof Error ? error.message : "No pudimos leer el archivo."); } finally { setCargando(false); } }
  async function confirmar() { if (!previsualizacion || !sedeId || !preparados.length || repetidos) return; setCargando(true); setMensaje(""); try { const respuesta = await fetch("/api/v1/compras/importacion/confirmar", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ filas: preparados, sedeId, proveedor }) }); const resultado = await respuesta.json(); if (!respuesta.ok || !resultado.ok) throw new Error(resultado.mensaje); toast.success(resultado.mensaje); cerrar(); router.refresh(); } catch (error) { setMensaje(error instanceof Error ? error.message : "No pudimos confirmar la compra."); } finally { setCargando(false); } }
  function cerrar() { setAbierto(false); setCargando(false); setPrevisualizacion(null); setAsociacion([]); setMensaje(""); }
  return <><button className="boton boton--secundario" type="button" onClick={() => setAbierto(true)}><Upload /> Importar</button>{abierto && <div className="dialogo-fondo" role="presentation"><section ref={dialogo} className="dialogo-importacion" role="dialog" aria-modal="true" aria-labelledby="titulo-importacion-compras"><header><div><small>CSV O EXCEL</small><h2 id="titulo-importacion-compras">Importar compra</h2></div><button type="button" className="accion-icono" onClick={cerrar} aria-label="Cerrar importación"><X /></button></header>{!previsualizacion ? <label className="selector-archivo">{cargando ? <LoaderCircle className="girando" /> : <FileSpreadsheet />}<strong>Elegí el archivo del proveedor</strong><span>Hasta 1.000 filas y 5 MB. Formatos .csv y .xlsx.</span><input type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={cargando} onChange={(e) => seleccionar(e.target.files?.[0])} /></label> : <><label>Proveedor<input value={proveedor} maxLength={160} onChange={(e) => setProveedor(e.target.value)} placeholder="Opcional" /></label><label>Local<select value={sedeId} onChange={(e) => setSedeId(e.target.value)}>{sedes.map((sede) => <option value={sede.id} key={sede.id}>{sede.nombre}</option>)}</select></label><p className="ayuda-importacion">Asociá cada columna y confirmá los productos que ingresarán al inventario.{previsualizacion.recortado && " Se muestran las primeras 1.000 filas."}</p><div className="asociacion-columnas">{previsualizacion.encabezados.map((encabezado, indice) => <label key={`${encabezado}-${indice}`}><span>{encabezado}</span><select value={asociacion[indice] ?? "ignorar"} onChange={(e) => setAsociacion((actual) => actual.map((campo, posicion) => posicion === indice ? e.target.value as CampoCompra : campo))}>{campos.map((campo) => <option value={campo.valor} key={campo.valor}>{campo.etiqueta}</option>)}</select></label>)}</div><div className="previsualizacion-importacion"><table><thead><tr>{previsualizacion.encabezados.map((encabezado, indice) => <th key={`${encabezado}-${indice}`}>{encabezado}</th>)}</tr></thead><tbody>{previsualizacion.filas.slice(0, 8).map((fila, indice) => <tr key={indice}>{previsualizacion.encabezados.map((_, columna) => <td key={columna}>{fila[columna] || "Sin dato"}</td>)}</tr>)}</tbody></table></div>{repetidos && <p role="alert">Cada dato debe corresponder a una sola columna.</p>}{preparados.length < previsualizacion.filas.length && <p className="ayuda-importacion">Se omitirán filas sin nombre, cantidad o costo válido.</p>}{mensaje && <p role="alert">{mensaje}</p>}<button className="boton boton--primario" type="button" disabled={cargando || !preparados.length || repetidos} onClick={confirmar}>{cargando ? "Registrando…" : `Confirmar ${preparados.length} productos`}</button></>}</section></div>}</>;
}
